name: poultrypro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  flutter_spinkit: ^5.2.2
  google_fonts: ^8.1.0
  lucide_icons_flutter: ^3.1.15
  path: ^1.9.1
  sqflite: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
